os: linux
dist: xenial
sudo: required
git:
  depth: 3
addons:
  apt:
    update:
    - true
install: true
script:
  - "travis_wait 30 sleep 1800 &"
  - chmod +x ./release.sh
  - bash ./release.sh
branches:
  only:
  - master
  except:
  - /^(?i:untagged)-.*$/
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
